### ISSUE TITLE
Add support for viewing DataFrames in Jupyter

### ISSUE THREAD

**Issue by jjbrosnan** [deephaven/deephaven-ipywidgets#4]
As a user, I want the ability to render DataFrames in Jupyter so that I can use this tool more often.  I prefer this tool for visualizing data, and sometimes I'm working with DataFrames instead of Deephaven tables.  I can convert them, but it would be nice to display data without having to do that.

**Comment by mofojed** [comment]
A snippet for creating a simple data frame:
```
import pandas as pd
data = {"X": [1, 2, 3], "Y": [1, 2, 3]}
df = pd.DataFrame(data)
```

Running in a Deephaven IDE, this shows the DataFrame in a Deephaven grid. However, we do not allow you to embed the item using embed-grid (since it is a different object type). Need to allow embed-grid to handle Pandas DataFrame objects correctly, then we can probably show it correctly by doing `display(DeephavenWidget(df))`

**Comment by mofojed** [comment]
We could update `embed-grid` to handle Pandas type DataFrames, or we could look at passing the entire data frame through the widget and avoid having to embed an iFrame entirely. Each approach have their advantages.
